import {
  cardVariants,
  darkTheme,
  lightTheme,
  typographyVariants,
} from '@scalewing/tokens';
import { actionBarClassCatalog } from './css-action-bar.js';
import { actionMenuClassCatalog } from './css-action-menu.js';
import { accordionClassCatalog } from './css-accordion.js';
import { switchClassCatalog } from './css-switch.js';
import { dateFieldClassCatalog } from './css-date-field.js';
import { calendarButtonClassCatalog } from './css-calendar-button.js';
import { checkboxClassCatalog } from './css-checkbox.js';
import { radioGroupClassCatalog } from './css-radio-group.js';
import { spinnerClassCatalog } from './css-spinner.js';
import { progressClassCatalog } from './css-progress.js';
import { tooltipClassCatalog } from './css-tooltip.js';
import { infoTipClassCatalog } from './css-info-tip.js';
import { separatorClassCatalog } from './css-separator.js';
import { statTileClassCatalog } from './css-stat-tile.js';
import { tabsClassCatalog } from './css-tabs.js';
import { responsiveClassCatalog } from './css-responsive.js';
import { filterChipsClassCatalog } from './css-filter-chips.js';
import { gridClassCatalog } from './css-grid.js';
import { gridSpanClassCatalog } from './css-grid-span.js';
import { denominationGridClassCatalog } from './css-denomination-grid.js';
import { scrollRegionClassCatalog } from './css-scroll-region.js';
import { fieldClassCatalog } from './css-field.js';
import { boxBorderClassCatalog } from './css-box-border.js';
import { cssComponentClasses } from './css-components.js';
import { buttonClassCatalog } from './css-button.js';
import { chartClassCatalog } from './css-chart.js';
import { dataClassCatalog } from './css-data.js';
import { segmentedClassCatalog } from './css-segmented.js';
import { tableClassCatalog } from './css-table.js';
import { chromeClassCatalog } from './css-chrome.js';
import { sectionNavClassCatalog } from './css-section-nav.js';
import { dialogClassCatalog } from './css-dialog.js';
import { selectClassCatalog } from './css-select.js';
import { splitClassCatalog } from './css-split.js';
import { toastClassCatalog } from './css-toast.js';
import { cssDocumentCanvas } from './css-document.js';
import { cssPaletteAttributes } from './css-palettes.js';
import { cssUtilities } from './css-utilities.js';
import { cssVariables } from './css-variables.js';
import {
  gapClassNames,
  layoutClassNames,
  paddingClassNames,
} from './spacing-classes.js';

export function utilityClassCatalog(): string[] {
  return [
    ...paddingClassNames(),
    ...gapClassNames(),
    ...layoutClassNames,
    'sw-card',
    ...cardVariants.map((variant) => `sw-card-${variant}`),
    'sw-truncate',
    'sw-text-align-start',
    'sw-text-align-center',
    'sw-text-align-end',
    'sw-tabular',
    ...Object.keys(typographyVariants).map((name) => `sw-text-${name}`),
    ...buttonClassCatalog(),
    ...dataClassCatalog(),
    ...segmentedClassCatalog(),
    ...tableClassCatalog(),
    ...scrollRegionClassCatalog(),
    ...chartClassCatalog(),
    ...chromeClassCatalog(),
    ...sectionNavClassCatalog(),
    ...dialogClassCatalog(),
    ...accordionClassCatalog(),
    ...selectClassCatalog(),
    ...actionMenuClassCatalog(),
    ...actionBarClassCatalog(),
    ...switchClassCatalog(),
    ...dateFieldClassCatalog(),
    ...calendarButtonClassCatalog(),
    ...checkboxClassCatalog(),
    ...radioGroupClassCatalog(),
    ...spinnerClassCatalog(),
    ...progressClassCatalog(),
    ...tooltipClassCatalog(),
    ...infoTipClassCatalog(),
    ...separatorClassCatalog(),
    ...statTileClassCatalog(),
    ...tabsClassCatalog(),
    ...filterChipsClassCatalog(),
    ...gridClassCatalog(),
    ...gridSpanClassCatalog(),
    ...denominationGridClassCatalog(),
    ...fieldClassCatalog(),
    ...splitClassCatalog(),
    ...toastClassCatalog(),
    ...responsiveClassCatalog(),
    ...boxBorderClassCatalog(),
  ];
}

export {
  generatePaletteStylesheet,
  paletteStylesheetIds,
} from './css-palettes.js';

export function generateStylesheet(): string {
  return `/* Generated by @scalewing/tokens. Do not edit by hand. */
${cssVariables(lightTheme, darkTheme)}

${cssPaletteAttributes()}

${cssDocumentCanvas()}

${cssUtilities()}

${cssComponentClasses()}
`;
}
