import { semanticColorKeys } from './colors.js';
import { createTheme } from './create-theme.js';
import {
  colorsForPalette,
  paletteHasStylesheet,
  palettesWithStylesheets,
  type PaletteId,
} from './palettes.js';
import { type ColorScheme } from './theme.js';

function paletteCustomProperties(id: PaletteId, scheme: ColorScheme): string {
  const overlay = colorsForPalette(id, scheme);
  const theme = createTheme({ colorScheme: scheme, palette: id });
  const lines: string[] = [];

  for (const key of semanticColorKeys) {
    if (overlay[key]) {
      lines.push(`  --sw-color-${key}: ${theme.colors[key]};`);
    }
  }

  lines.push(`  --sw-glass-blur: ${theme.glass.blur}px;`);
  lines.push(`  --sw-glass-saturate: ${theme.glass.saturate};`);
  lines.push(`  --sw-glass-fill: ${theme.glass.fill};`);
  lines.push(`  --sw-glass-border: ${theme.glass.border};`);
  lines.push(`  --sw-glass-specular: ${theme.glass.specular};`);

  return lines.join('\n');
}

export function cssPaletteAttributes(): string {
  return palettesWithStylesheets()
    .map((palette) => {
      const light = paletteCustomProperties(palette.id, 'light');
      const dark = paletteCustomProperties(palette.id, 'dark');
      return `[data-theme='light'][data-palette='${palette.id}'] {
${light}
}

[data-theme='dark'][data-palette='${palette.id}'] {
${dark}
}`;
    })
    .join('\n\n');
}

export function generatePaletteStylesheet(id: PaletteId): string {
  if (!paletteHasStylesheet(id)) {
    throw new Error(
      `Palette ${id} is the default and has no overlay stylesheet`,
    );
  }

  const light = paletteCustomProperties(id, 'light');
  const dark = paletteCustomProperties(id, 'dark');

  return `/* Generated by @scalewing/tokens. Do not edit by hand. */
:root,
[data-theme='light'] {
${light}
}

[data-theme='dark'] {
${dark}
}
`;
}

export function paletteStylesheetIds(): PaletteId[] {
  return palettesWithStylesheets().map((palette) => palette.id);
}
