import { cssComponentClasses } from './css-components.js';
import { cssUtilities } from './css-utilities.js';
import { cssVariables } from './css-variables.js';
import {
  gapClassNames,
  layoutClassNames,
  paddingClassNames,
} from './spacing-classes.js';
import { darkTheme, lightTheme } from './theme.js';
import { typographyVariants } from './typography.js';

export function utilityClassCatalog(): string[] {
  return [
    ...paddingClassNames(),
    ...gapClassNames(),
    ...layoutClassNames,
    'sw-card',
    'sw-card-elevated',
    'sw-truncate',
    ...Object.keys(typographyVariants).map((name) => `sw-text-${name}`),
  ];
}

export function generateStylesheet(): string {
  return `/* Generated by @scalewing/tokens. Do not edit by hand. */
${cssVariables(lightTheme, darkTheme)}

${cssUtilities()}

${cssComponentClasses()}
`;
}
