import { actionMenuClassCatalog } from './css-action-menu.js';
import { accordionClassCatalog } from './css-accordion.js';
import { switchClassCatalog } from './css-switch.js';
import { dateFieldClassCatalog } from './css-date-field.js';
import { checkboxClassCatalog } from './css-checkbox.js';
import { radioGroupClassCatalog } from './css-radio-group.js';
import { spinnerClassCatalog } from './css-spinner.js';
import { cssComponentClasses } from './css-components.js';
import { buttonClassCatalog } from './css-button.js';
import { chartClassCatalog } from './css-chart.js';
import { dataClassCatalog } from './css-data.js';
import { chromeClassCatalog } from './css-chrome.js';
import { dialogClassCatalog } from './css-dialog.js';
import { selectClassCatalog } from './css-select.js';
import { splitClassCatalog } from './css-split.js';
import { toastClassCatalog } from './css-toast.js';
import { cssDocumentCanvas } from './css-document.js';
import { cssPaletteAttributes } from './css-palettes.js';
import { cssUtilities } from './css-utilities.js';
import { cssVariables } from './css-variables.js';
import { cardVariants } from './card.js';
import {
  gapClassNames,
  layoutClassNames,
  paddingClassNames,
} from './spacing-classes.js';
import { darkTheme, lightTheme } from './theme.js';
import { typographyVariants } from './typography.js';

export function utilityClassCatalog(): string[] {
  return [
    ...paddingClassNames(),
    ...gapClassNames(),
    ...layoutClassNames,
    'sw-card',
    ...cardVariants.map((variant) => `sw-card-${variant}`),
    'sw-truncate',
    'sw-tabular',
    ...Object.keys(typographyVariants).map((name) => `sw-text-${name}`),
    ...buttonClassCatalog(),
    ...dataClassCatalog(),
    ...chartClassCatalog(),
    ...chromeClassCatalog(),
    ...dialogClassCatalog(),
    ...accordionClassCatalog(),
    ...selectClassCatalog(),
    ...actionMenuClassCatalog(),
    ...switchClassCatalog(),
    ...dateFieldClassCatalog(),
    ...checkboxClassCatalog(),
    ...radioGroupClassCatalog(),
    ...spinnerClassCatalog(),
    ...splitClassCatalog(),
    ...toastClassCatalog(),
  ];
}

export {
  generatePaletteStylesheet,
  paletteStylesheetIds,
} from './css-palettes.js';

export function generateStylesheet(): string {
  return `/* Generated by @scalewing/tokens. Do not edit by hand. */
${cssVariables(lightTheme, darkTheme)}

${cssPaletteAttributes()}

${cssDocumentCanvas()}

${cssUtilities()}

${cssComponentClasses()}
`;
}
