import { cssComponentClasses } from './css-components.js';
import { buttonClassCatalog } from './css-button.js';
import { cssDocumentCanvas } from './css-document.js';
import { cssUtilities } from './css-utilities.js';
import { cssVariables } from './css-variables.js';
import { cardVariants } from './card.js';
import {
  gapClassNames,
  layoutClassNames,
  paddingClassNames,
} from './spacing-classes.js';
import { darkTheme, lightTheme } from './theme.js';
import { typographyVariants } from './typography.js';

export function utilityClassCatalog(): string[] {
  return [
    ...paddingClassNames(),
    ...gapClassNames(),
    ...layoutClassNames,
    'sw-card',
    ...cardVariants.map((variant) => `sw-card-${variant}`),
    'sw-truncate',
    ...Object.keys(typographyVariants).map((name) => `sw-text-${name}`),
    ...buttonClassCatalog(),
  ];
}

export function generateStylesheet(): string {
  return `/* Generated by @scalewing/tokens. Do not edit by hand. */
${cssVariables(lightTheme, darkTheme)}

${cssDocumentCanvas()}

${cssUtilities()}

${cssComponentClasses()}
`;
}
